spring:
  application:
    name: front-service

---
spring:
  config:
    activate:
      on-profile: dev

    import: optional:configserver:http://${username}:${password}@localhost:9000

websocket:
  url: http://localhost:8081/connect

logging:
  config: classpath:logback-dev.xml

---
spring:
  config:
    activate:
      on-profile: live
      
    import: optional:configserver:http://${secrets.username}:${secrets.password}@config-server:9000

logging:
  config: classpath:logback-live.xml