spring:
  application:
    name: front-service

  profiles:
    active: dev

  config:
    import: optional:configserver:http://${username}:${password}@localhost:9000
  jwt:
    token:
      access-expiration-time: 600
      refresh-expiration-time: 1200
server:
  port: 8580

gateway:
  url: http://localhost:8080

